Databases:
  CustomDataset: dataset/audios/{uri}.wav

Protocols:
  CustomDataset:
    SpeakerDiarization:
      default:
        scope: file
        train:
          uri: dataset/lists/train.txt
          annotation: dataset/rttms/train/{uri}.rttm
          annotated: dataset/uems/train/{uri}.uem
        development:
          uri: dataset/lists/dev.txt
          annotation: dataset/rttms/dev/{uri}.rttm
          annotated: dataset/uems/dev/{uri}.uem
        test:
          uri: dataset/lists/test.txt
          annotation: dataset/rttms/test/{uri}.rttm
          annotated: dataset/uems/test/{uri}.uem